server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    poolName: demo-pool
    autoCommit: false
  security:
    user:
      name: admin
      password: 123456
management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
actuator:
  security:
    endpoints: "*"
logging:
  level:
    root: debug
  path: ${LOG_HOME:/tmp/logs}


giltab:
  url: gitlab.ccbft.com #128.195.53.249
  token: ${PRIVATE-TOKEN:123456789}
info:
  application:
    name: ${spring.application.name}
    description: A Demo for Spring Boot hello World!
    author:
      name: jerry
      bio: Nuclear Safety Inspector, Former Technical Supervisor
  