spring:
  profiles:
    active: sit
  application:
    name: devops-demo
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/traffic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Admin@123}
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      minimumIdle: 5