management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: debug
  path: ${LOG_HOME:/home/ap/logs}