server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    poolName: pool
    autoCommit: false
management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: debug
  path: ${LOG_HOME:/opt/logs}