apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- toolbox.yaml
- httproute.yaml
# add common labels
labels:
- includeSelectors: true
  pairs:
    app: coloring